-- MySQL Script generated by MySQL Workbench
-- 06/03/19 14:07:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema starwars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starwars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starwars` DEFAULT CHARACTER SET utf8 ;
USE `starwars` ;

-- -----------------------------------------------------
-- Table `starwars`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`people` (
  `name` VARCHAR(45) NOT NULL,
  `height` VARCHAR(45) NOT NULL,
  `mass` VARCHAR(45) NOT NULL,
  `hair_color` VARCHAR(45) NOT NULL,
  `skin_color` VARCHAR(45) NOT NULL,
  `birthyear` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `starwars`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`species` (
  `name` VARCHAR(45) NOT NULL,
  `classification` VARCHAR(45) NOT NULL,
  `designation` VARCHAR(45) NOT NULL,
  `average_height` VARCHAR(45) NOT NULL,
  `skin_color` VARCHAR(45) NOT NULL,
  `hair_colors` VARCHAR(45) NOT NULL,
  `eye_colors` VARCHAR(45) NOT NULL,
  `average_lifespan` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
